---
- name: parse IPs
  hosts: all
  become: true

  vars:
    domain: example.com 

  tasks:
  - name: Build hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: '{{ hostvars[item].ansible_eth0.ipv4.address }} {{item}} {{item}}.{{ domain }}'
      state: present
      create: yes
    with_items: '{{ groups["all"]|default([]) }}'
    become: true
    ignore_errors: true
